config/routes.rb
Rails.application.routes.draw do

  get 'historique/index'
  resources :payments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 root "hospitals#index"
  get "historique", to: "historique#index"
  devise_for :users

  resources :hospitals
  resources :comments, only: [:create]
  resources :prestations
  resources :users, only: [:show]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
    post 'users/guest_admin_sign_in', to: 'users#new_admin_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :hospital
  has_many :payment, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name_prest, presence:true
  validates :price, presence:true
end

app/controllers/prestations_controller.rb
class PrestationsController < ApplicationController
  before_action :set_prestation, only: %i[ show edit update destroy ]

  # GET /prestations or /prestations.json
  def index
    @prestations = Prestation.all
  end

  # GET /prestations/1 or /prestations/1.json
  def show
  end

  # GET /prestations/new
  def new
    @prestation = Prestation.new
  end

  # GET /prestations/1/edit
  def edit
  end

  # POST /prestations or /prestations.json
  def create
    if user_signed_in?
      if current_user.role?
        @prestation = Prestation.new(prestation_params)

        respond_to do |format|
          if @prestation.save
            format.html { redirect_to @prestation, notice: "Prestation was successfully created." }
            format.json { render :show, status: :created, location: @prestation }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @prestation.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /prestations/1 or /prestations/1.json
  def update
    respond_to do |format|
      if @prestation.update(prestation_params)
        format.html { redirect_to @prestation, notice: "Prestation was successfully updated." }
        format.json { render :show, status: :ok, location: @prestation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prestation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestations/1 or /prestations/1.json
  def destroy
    @prestation.destroy
    respond_to do |format|
      format.html { redirect_to prestations_url, notice: "Prestation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prestation
      @prestation = Prestation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prestation_params
      params.require(:prestation).permit(:name_prest, :price, :hospital_id)
    end
end

app/helpers/prestations_helper.rb
module PrestationsHelper
end

app/views/prestations/_form.html.erb
<br/><br/>
<section id="features" class="services-area pt-120">
<%= form_with(model: prestation, local: true) do |form| %>
  <% if prestation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prestation.errors.count, "error") %> prohibited this prestation from being saved:</h2>

      <ul>
      <% prestation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_prest %>
    <%= form.text_field :name_prest, placeholder: "prestation name" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, placeholder: "montant" %>
  </div>

  <div class="field">
  <%= form.label :choix %>
  <%= form.collection_select :hospital_id, Hospital.order(:hospi_name),:id,:hospi_name, include_blank: true, placeholder: "choix d'hôpital" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</section>

app/views/prestations/edit.html.erb
<h1>Editing Prestation</h1>

<%= render 'form', prestation: @prestation %>

<%= link_to 'Show', @prestation %> |
<%= link_to 'Back', prestations_path %>

app/views/prestations/index.html.erb
<br/><br/>
<section id="features" class="services-area pt-120">
<p id="notice"><%= notice %></p>
<div class="container">
      <h1><%= I18n.t('views.messages.prest') %></h1>
      <table class="table table-dark">
        <thead>
        <tr>
        <th><%= I18n.t('views.messages.nameA') %></th>
        <th><%= I18n.t('views.messages.price') %></th>
        <th><%= I18n.t('views.messages.hospi') %></th>
        <th colspan="3"></th>
      </tr>
        </thead>
        <tbody>
        <% @prestations.each do |prestation| 
          prest=prestation.hospital%>
          <tr>
            <td><%= prestation.name_prest %></td>
            <td><%= prestation.price %></td>
            <td><%= prest.hospi_name %></td>
            <td><%= link_to I18n.t('views.buttons.watchYet'), prestation, class: "badge bg-success", style:"font-size: 12px" %></td>
            <td><%= link_to I18n.t('views.buttons.edit'), edit_prestation_path(prestation), class: "badge bg-warning", style:"font-size: 12px"  %></td>
            <td><%= link_to I18n.t('views.buttons.delete'), prestation, method: :delete, data: { confirm: 'Are you sure?' }, class: "badge bg-danger", style:"font-size: 12px" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

<br>

<%= link_to I18n.t('views.buttons.addPrestation'), new_prestation_path , class: "badge bg-primary", style:"font-size: 12px" %></section>

app/views/prestations/new.html.erb
<h1>New Prestation</h1>

<%= render 'form', prestation: @prestation %>

<%= link_to 'Back', prestations_path %>

app/views/prestations/show.html.erb
<br/><br/>
<section id="features" class="services-area pt-120">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name prest:</strong>
  <%= @prestation.name_prest %>
</p>

<p>
  <strong>Price:</strong>
  <%= @prestation.price %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @prestation.hospital.hospi_name %>
</p>

<%= link_to 'Edit', edit_prestation_path(@prestation) %> |
<%= link_to 'Back', prestations_path %>

</section>