config/routes.rb
Rails.application.routes.draw do

  get 'historique/index'
  resources :payments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 root "hospitals#index"
  get "historique", to: "historique#index"
  devise_for :users

  resources :hospitals
  resources :comments, only: [:create]
  resources :prestations
  resources :users, only: [:show]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
    post 'users/guest_admin_sign_in', to: 'users#new_admin_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/historique_controller.rb
class HistoriqueController < ApplicationController
  def index
    if user_signed_in?
      @payments = Payment.where(user_id: current_user.id).all

      @comment = Comment.new
    end
  end
end

app/helpers/historique_helper.rb
module HistoriqueHelper
end

app/views/historique/index.html.erb
<br/><br/>
<br/><br/>
<br/><br/>

<div class="wrapperJ">
<p id="notice"><%= notice %></p>
  <h2><%= I18n.t('views.messages.histo') %></h2>
  <div class="tableJ">

    <div class="rowJ headerJ blueJ">
      <div class="cellJ">
      <%= I18n.t('views.messages.par') %>
      </div>
      <div class="cellJ">
      <%= I18n.t('views.messages.date') %>
      </div>
      <div class="cellJ">
      <%= I18n.t('views.messages.avis') %>
      </div>
    </div>

<% @payments.each do |value| 
        pay= Prestation.find(value.prestation_id) 
        host = pay.hospital%>
    <div class="rowJ">
      <div class="cellJ" data-title="Username">
      <%= host.hospi_name %>
      </div>
      <div class="cellJ" data-title="Password">
      <%= host.created_at %>
      </div>
      <div class="cellJ" data-title="Active">
      <button data-toggle="modal" data-target="#formulaire" class="btn btn-primary">Commentaire</button>
      
      <div class="modal fade" id="formulaire">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h4 class="modal-title">Votre avis sur la prestation :</h4>              
                  <button type="button" class="close" data-dismiss="modal">
                  <span>&times;</span>
                  </button>
              </div>
              <div class="modal-body row">
                  <%= form_with(model: @comment, local: true ,url: comments_path ) do |form| %>
                      <div class="form-group">
                          <%= form.label :opinion, for: "comment", class: "form-control-label" %>
                          <%= form.text_area :opinion, class: "form-control", id: "comment", placeholder: "Votre Commentaire" %>
                      </div>
                          <%= form.hidden_field :user_id, value: current_user.id %>
                          <%= form.hidden_field :user_id, value: current_user.id %>
                          <%= form.hidden_field :prestation_id, value: value.prestation_id %>
                  <button type="submit">Point de vue</button> 
                  <%end%>
              </div>
          </div>
      </div>
  </div>
      
      
      </div>
    </div>
<%end%>


  </div>

</div>

<script src="sample.js"></script>