config/routes.rb
Rails.application.routes.draw do

  get 'historique/index'
  resources :payments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 root "hospitals#index"
  get "historique", to: "historique#index"
  devise_for :users

  resources :hospitals
  resources :comments, only: [:create]
  resources :prestations
  resources :users, only: [:show]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users#new_guest'
    post 'users/guest_admin_sign_in', to: 'users#new_admin_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hospital.rb
class Hospital < ApplicationRecord
    has_many :prestations, dependent: :destroy
    validates :hospi_name, presence:true
    validates :hospi_adresse, presence:true
    def self.search(search)
        if search
          where('hospi_name LIKE ?', "%#{search}%")
        else
          all
        end
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: %i[ show edit update destroy ]

  # GET /hospitals or /hospitals.json
  def index
    @hospitals = Hospital.search(params[:search])

   
  end

  def search
    @hospitals =Hospital.name_search(params[:search_hospital])
  end

  # GET /hospitals/1 or /hospitals/1.json
  def show
    @payment = Payment.new
    @comments = Comment.all
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals or /hospitals.json
  def create
    if user_signed_in?
      if current_user.role?
        @hospital = Hospital.new(hospital_params)

        respond_to do |format|
          if @hospital.save
            format.html { redirect_to @hospital, notice: "Hospital was successfully created." }
            format.json { render :show, status: :created, location: @hospital }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @hospital.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /hospitals/1 or /hospitals/1.json
  def update
    if user_signed_in?
      if current_user.role?
        respond_to do |format|
          if @hospital.update(hospital_params)
            format.html { redirect_to @hospital, notice: "Hospital was successfully updated." }
            format.json { render :show, status: :ok, location: @hospital }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @hospital.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # DELETE /hospitals/1 or /hospitals/1.json
  def destroy
    if user_signed_in?
      if current_user.role?
        @hospital.destroy
        respond_to do |format|
          format.html { redirect_to hospitals_url, notice: "Hospital was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hospital_params
      params.require(:hospital).permit(:hospi_name, :hospi_adresse)
    end

end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<br/><br/>
<section id="features" class="services-area pt-120">
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hospi_name %>
    <%= form.text_field :hospi_name, placeholder: "Nom d'hôpital" %>
  </div>

  <div class="field">
    <%= form.label :hospi_adresse %>
    <%= form.text_field :hospi_adresse, placeholder: "Adresse d'hôpital" %>
  </div>

  <div class="actions">
    <%= form.submit, style:"font-size: 12px" %>
  </div>
<% end %>
</section>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<br/><br/>
<br/><br/>
<br/><br/>
<div class="app-container">
<p id="notice"><%= notice %></p>
<div class="app-content">
  <div class="projects-section">
    <div class="projects-section-header">
      <p><%= @hospital.hospi_name %></p>
      <p class="time"><%= @hospital.hospi_adresse %></p>
    </div>
    <div class="projects-section-line">
      <div class="projects-status">
        <div class="item-status">
          <span class="status-number"><%= @hospital.prestations.count %></span>
          <span class="status-type">Prestations</span>
        </div>
      </div>
    </div>
    <div class="project-boxes jsGridView">
    <% if @hospital.prestations %>
    <% @hospital.prestations.each do |value| %>
      <div class="project-box-wrapper">
        <div class="project-box" style="background-color:  #e9e7fd;;">
          <div class="project-box-header">
            <span><a href="../recu.webp" download="recu.webp">Demander un QR de paiement</a></span>
            <div class="more-wrapper">
              <button class="project-btn-more">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-more-vertical">
                  <circle cx="12" cy="12" r="1" />
                  <circle cx="12" cy="5" r="1" />
                  <circle cx="12" cy="19" r="1" />
                </svg>
              </button>
            </div>
          </div>
          <div class="project-box-content-header">
            <p class="box-content-header"><%= value.name_prest %></p>
            <p class="box-content-subheader"><%= value.price %> FCFA</p>
          </div>
          <div class="box-progress-wrapper">
            <p class="box-progress-header">Qualité</p>
            <div class="box-progress-bar">
              <span class="box-progress" style="width: 60%; background-color: #ff942e"></span>
            </div>
            <p class="box-progress-percentage">60%</p>
          </div>
          <div class="project-box-footer">
            <div class="participants">
              <img
                src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2550&q=80"
                alt="participant">
              <img
                src="https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTB8fG1hbnxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60"
                alt="participant">
            </div>
            <button id="pay-btn" class="days-left" style="color: #ff942e;"
          data-transaction-amount= <%= value.price %>
          data-transaction-description="Paiement de prestation">Payer </button>
          <%= form_with(model: @payment, local: true ,url: payments_path ) do |form| %>
            <% if user_signed_in? %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <%end%>
            <%= form.hidden_field :prestation_id, value: value.id %>
           <button type="submit" class="days-left" style="color: blue;">Valider la transaction</button> 
          <%end%>
          </div>
        </div>
      </div>
      <%end%>
    <%end%>
    </div>
    
  </div>
  <div class="messages-section">
    <button class="messages-close">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-x-circle">
        <circle cx="12" cy="12" r="10" />
        <line x1="15" y1="9" x2="9" y2="15" />
        <line x1="9" y1="9" x2="15" y2="15" />
      </svg>
    </button>
    <div class="projects-section-header">
      <p>Commentaires</p>
    </div>
    <div class="messages">
    <% @hospital.prestations.each do |value| %>
      <% value.comments.each do |comment| 
        user= User.find(comment.user_id)%>
        <div class="message-box">
          <img
            src="/assets/img/pro.png"
            alt="profile image">
          <div class="message-content">
            <div class="message-header">
              <div class="name"><%= user.name %></div>
            </div>
            <p class="message-line">
             <%= comment.opinion %>
            </p>
            <p class="message-line time">
            <%= comment.created_at %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">
   FedaPay.init('#pay-btn', { public_key: 'pk_live_4Wbtx5-rDoIQMhe2aVb4ZxmE' });
</script>